### PR TITLE
Add engine installer

### PR DESCRIPTION
**Pull request by jamesmkur**
@botandrose I didn't see the see my commits on this branch (though it looks like other commits from today made it over), so I'm opening this PR to get them in.

From https://github.com/botandrose/calagator/pull/2:
- updates gemspec to loosen dependency versions
- move SecretsReader.read to engine.rb where it can be initialized
- add installer, secrets sample
- document installation

### CODE REVIEW

**Comment by botandrose** [comment]
Weird, not sure how we lost these commits in the move, good catch! Probably my fault. In any event, needs a rebase before I can merge.

I was thinking, though, and ideally, the tests would exercise this functionality to make sure we don't break it in the future. I wonder if its possible for tests to start with a nearly stock rails install in spec/dummy, then run this generator, and finally run all the tests. What do you think?

**Comment by botandrose** [comment]
Just thought about this some more, and I think we could push this even further. We could wrap this piece in an even higher level: a `calagator` binary. I'm imagining something like:

```
$ gem install calagator
$ calagator new path/to/calagator
```

This would `rails new` the path, then cd in and run this generator in it. Bam, fully-functional, Heroku-ready calagator instance. We could also dogfood this to generate the dummy app in `spec/dummy`, to cover the whole shebang and ensure there are no incidental artifacts checked into the dummy app that are needed for this easy workflow.

This is almost certainly out of scope for this PR, but I wanted to bring it up for discussion.

**Comment by jamesmkur** [comment]
@botandrose Re: testing the installer: that's a good point, though I don't know how we would do it in `spec/dummy`. That should be a fully functional implementation with as many edge cases as we wish to test. Maybe we can create a `spec/installer_dummy` that contains a base rails app, then the tests could run the installation and a test everything we'd expect in a vanilla install? That could drastically increase the time our tests take though. A quick search around the interwebs shows some other possible solutions we could look into (https://github.com/stevehodgkiss/generator_spec).

Re: the binary: I think that's a great idea, but yeah, out of this PRs scope. Also the installer and binary aren't mutually exclusive, running this installer as a step in the binary is a possibility. Rails generators are powered with Thor, which is good at running tasks and manipulating files (also a possibility for the binary).

I'll rebase and add the initializer setup from #312 today.

thanks!

**Comment by botandrose** [comment]
@jamesmkur Cool. Note that d2c3c2e removed the `timezone` and `precompile_assets` mattrs.

Once this is ready to go and merged, I'll do some experimentation with testing the installer and the binary. I suspect we can have our cake and eat it too...

**Comment by jamesmkur** [comment]
@botandrose Thx, I was going to that very thing. Adding `config.time_zone = Calagator.timezone` me chuckle, a config to set a config.

**Comment by jamesmkur** [comment]
@botandrose PR updated with the install setting up the initializer and a small refactor of the settings in `engine.rb` (gotta love 2am commits).

thanks

**Comment by botandrose** [comment]
Made two small notes, looks great otherwise, though! Should be good to merge after those are addressed.

**Comment by jamesmkur** [comment]
@botandrose good catch, I was assuming self was implied in the `class << self` block and passing test gave me false confidence :) I added some settings specs for good measure.

**Comment by botandrose** [comment]
@jamesmkur Yeah, definitely a bit of a gotcha in Ruby. Everything looks good, though! Thanks!

**Pull request merged**
