### PR TITLE
Eliminate line-hight style from .single_event h3

### PR DESCRIPTION
**Pull request by nblackburn87**
This should fix issue #293. I've poked around to make sure it's not going to break anything else and seems good to go. @reidab @shawnacscott

### CODE REVIEW

**Comment by nblackburn87** [comment]
Merge please @reidab or @aeschright ?

**Comment by reidab** [comment]
I haven't merged this one yet because it includes a commit from #322, so I was trying to get that one merged first.

**Comment by reidab** [comment]
I'm going to go work on these before the Ruby meeting tonight, so it should be done soon. :)

**Comment by reidab** [comment]
Merged manually

**Pull request closed without merging**
