### PR TITLE
Enable fast_finish in travis config

### PR DESCRIPTION
**Pull request by reidab**

### CODE REVIEW

**Comment by botandrose** [comment]
18m vs 33m! <3

**Comment by jc00ke** [comment]
Where did you find this? Or, maybe a better question: how have I not seen this before?

**Comment by reidab** [comment]
Down at the veeeeerrrrry bottom of http://docs.travis-ci.com/user/build-configuration/

**Comment by botandrose** [comment]
Looks like its only a little over a year old: http://blog.travis-ci.com/2013-11-27-fast-finishing-builds/

**Pull request merged**
