### PR TITLE
Search functionality on small screen

### PR DESCRIPTION
**Pull request by davidmolina**
@shawnacscott - here you go.

### CODE REVIEW

**Comment by shawnacscott** [comment]
thanks, @davidmolina! I want to look at this on my system and make sure it fixes the whole problem before merge. I'll try and get to it this weekend.

Also, don't forget to add yourself to the [contributors list](https://github.com/calagator/calagator/blob/master/CONTRIBUTORS.md)!

**Comment by davidmolina** [comment]
@shawnacscott - awesome! 

Will add myself to the contributors list. Thanks!

**Comment by shawnacscott** [comment]
@davidmolina This definitely fixes the missing box, thanks!

It would be nice, though, if the search box maintained the same appearance on both the mobile and standard layouts. That can be achieved by:

````
// In app/assets/stylesheets/calagator/mobile.scss
// Adding this line to #search_form input:
border: 3px solid light-gray;

// Changing #search_field to:
width: 121px;
````

In addition, if you can remove the extraneous commented out code on lines 89-95, that would be great.

Thanks again for your contribution!

**Comment by davidmolina** [comment]
I'm on it!

**Comment by reidab** [comment]
It looks from the comments like there still might be a few tweaks in progress on this one? @davidmolina please let me know when this is ready for review/merging.

**Comment by davidmolina** [comment]
@reidab will jump on and tweak. will let you know. thx.

**Comment by aeschright** [comment]
@davidmolina Do you have an update on this? Let us know if you'd like assistance, or to hand off part of the work.

**Comment by davidmolina** [comment]
Handoff would be good. 

-David

**Comment by reidab** [comment]
Looks like this work was wrapped up in #407.

**Pull request closed without merging**
