### PR TITLE
Add admin tools for managing events

### PR DESCRIPTION
**Pull request by aeschright**
Not the prettiest UI! But this provides:
- a central area for admin-related content
- optional access control through basic auth
- an interface for locking and unlocking events for editing and deletion
- an update to the event pages to indicate an event has been locked

### CODE REVIEW

**Comment by shawnacscott** [comment]
@botandrose @jc00ke if you all can look at this, it would be very appreciated. This is extremely high priority, and the faster this can get merged, the better. Thanks!

**Comment by shawnacscott** [comment]
I assume Travis is failing because Secrets isn't available to that test with the .sample extension?

**Comment by jc00ke** [comment]
Can't comment inline from the mobile view, but 2 things: 

1) spec fails and whole CI is red :(
2) `return false if locked` is a bit verbose for my tastes, but reads nicely. I wouldn't mind seeing it changed to something more terse, like `!locked` but not a stopper.

**Comment by botandrose** [comment]
IMO, the code looks great. Nice, simple, and readable. I'd like to see an acceptance test that describes the workflow and makes sure everything is wired up correctly, and some unit tests that cover the new locking functionality on `Event.`

**Comment by aeschright** [comment]
@botandrose I added more specs for the event locking behavior, but I don't think I'll be able to do an acceptance test today. Seem ok to go ahead and merge, and we'll follow up on the rest later?

**Comment by botandrose** [comment]
Thanks @aeschright, I'll see if I can fire out an acceptance test for it real quick-like.

**Comment by botandrose** [comment]
@aeschright I just pushed two acceptance tests, one for admin auth, and one for event locking. However, it appears that the locking functionality does not currently work. Clicking the "Lock" button generates the success flash message, but the event remains unlocked. The acceptance test exposes this failure.

**Comment by aeschright** [comment]
I must have changed something else after my last test through the UI. Looking into it now.

**Comment by aeschright** [comment]
@botandrose The changes I made fixed the feature test for me locally, but I'm still getting failures on TravisCI. Any suggestions?

**Comment by botandrose** [comment]
@aeschright Hmm seems like the auth test is flaky... I'll take a look at that now.

However, it appears that one can still successfully change a locked event by appending "/edit" to the event's url.

**Comment by botandrose** [comment]
It looks like that test is somehow run-order dependent. I can replicate the failure locally by specifying the same rspec randomization seed that failed on travis, e.g. `rspec --seed 20582`, FYI.

**Comment by botandrose** [comment]
@aeschright Okay, `spec/features/admin_auth_spec.rb` failure is due to `spec/controllers/admin_controller_spec.rb` setting global state in the before hook:

```ruby
  before do
    SECRETS.admin_username = nil
    SECRETS.admin_password = nil
  end
```

`SECRETS` is effectively global, so this leaks out of that spec into others. So, if the latter spec file is run before the former, the user/pass will be set to nil, and basic auth will be disabled. You could address this by using an around hook to reset those values back to their original value after the test, but IMO the `spec/controllers/admin_controller_spec.rb` isn't really providing much value on its own, so I'd just delete it. Your call.

**Comment by aeschright** [comment]
@botandrose I think I've got everything working now, and I added a filter and tests for the controllers as you suggested. Thanks for the help!

**Comment by botandrose** [comment]
:thumbsup:

**Comment by botandrose** [comment]
Quick note that `Event#verify_lock_status` can probably be removed, now that the locking is handled entirely in the controller.

**Comment by shawnacscott** [comment]
Looks like `admin_auth_spec.rd:18` is still flakey. @fterdal discovered this running the suite with seed 44757. Sometimes it returns a 304 instead of 200. Thoughts?

**Comment by reidab** [comment]
Are you sure it's not responding with a 403 (Forbidden)? A 304 would be related to caching and is even more unexpected.

**Comment by botandrose** [comment]
#340

**Comment by reidab** [comment]
Wow, it was indeed 304. Weirdness.

**Pull request merged**
