### PR TITLE
Test MRI 2.2.0 on Travis

### PR DESCRIPTION
**Pull request by reidab**

### CODE REVIEW

**Comment by reidab** [comment]
It looks like there isn't currently a released version of Rails 3.2.x that supports Ruby 2.2, but one might be released the next time a 3.2 security issue comes up. (https://github.com/rails/rails/pull/18306)

I'm more inclined to upgrade Calagator to the latest 4-series Rails ( #180 ) than to chase these 3.2 patches.

**Comment by shawnacscott** [comment]
That sounds useful to me. We've been waiting for a paper trail manager
upgrade for over six months at this point, and I pinged them again a month
ago in fusion94/paper_trail_manager#6 so we need to consider other options
to make that happen. Any chance we can bring that gem back in house as a
Calagator project if we depend on it so heavily? Otherwise, what would be
involved in removing it from the project? If neither of those are feasible,
what other options are there?

**Comment by reidab** [comment]
I'm happy to put in the work to update paper_trail_manager. We'll submit a PR, and if that doesn't work, we'll take things back in-house with a fork.

**Comment by shawnacscott** [comment]
Sounds good to me!

**Pull request closed without merging**
