### PR TITLE
Imported event URLs

### LINKED ISSUE #487: Imported events with > 3 URLs in description are uneditable
One of our current spam-fighting measures is a limit on the number of links allowed in an event's description. We don't enforce this limit when importing events, since the user doesn't have control over the import source. If an event is imported with more URLs than the allowed limit, subsequent attempts to edit it are rejected.

## Repro

1. Import an event with many links: http://www.meetup.com/laruby/events/226450232/
2. Attempt to edit the event

### PR DESCRIPTION
**Pull request by supremebeing7**
This fixes #487 using the approach discussed.

### CODE REVIEW

**Comment by botandrose** [comment]
Wow, this is a really good-looking PR. Great work! Only feedback I have is that perhaps the tests should be at the unit level, since this is an edge case, not the happy path. Either way, :+1:

**Comment by botandrose** [comment]
Oh, and those extracted methods should probably be marked private.

**Comment by supremebeing7** [comment]
@botandrose Thanks for the notes.

RE: extracted methods marked as private - They are still under the `private` label on line 20, doesn't that suffice? Or do we want to explicitly mark each private method as `private` going forward? I was just conforming to what was already present.

RE: unit level tests -- I am not seeing any unit testing for Event::Saver, or any type of saving of events. Am I missing it? If not, I can definitely create an event_saver_spec. I generally don't unit test private methods, but it would probably be a good idea to unit test the two public methods in Event::Saver, which would then give coverage for the new stuff I added. Whatever y'all think, I'm good with.

**Comment by botandrose** [comment]
Oh, good catch. They are indeed private. I didn't see private in the diff so I just assumed it was public scope. Derp!

Yeah, when I extracted `Event::Saver`, I should have extracted the relevant tests from the controller test, too, but I didn't :(, so having a spec file that exercises `Event::Saver` directly would be a step forward.

So yeah, if you can unit test this functionality directly on `Event::Saver` through its public API, I think that would be the right way to go about it. I def agree about not testing private methods, btw.

**Comment by supremebeing7** [comment]
Cool. Yeah I can get that going as part of this PR.

**Comment by supremebeing7** [comment]
Ok, I've changed the feature specs I added into unit tests on Event::Saver. Let me know if you have any more notes.

**Comment by reidab** [comment]
It looks like one of the `Event::Saver` specs in the final version here is failing Travis consistently on Rails 4.0 and 4.1, but passing on Rails 4.2.

**Comment by supremebeing7** [comment]
OK, Green. Not exactly sure the root cause, but dirty-checking wasn't working the way I was re-assigning the event.description value, so had to pass it through the params. The test more closely follows the actual flow of the app now, though, so that's a win.

**Comment by botandrose** [comment]
LGTM! :+1:

**Pull request merged**
