### PR TITLE
Use Webmock to isolate tests from the network

### PR DESCRIPTION
**Pull request by botandrose**
Replaced all the network-related mocks and stubs with Webmock. This is great, because now our tests know much less about the internals of the objects under test, enabling easier refactoring. Was also able to remove a few methods that only existed as seams for stubbing network responses. Lastly, Webmock exposed an unnecessary http request happening in all parsers, so that was removed, which should increase performance.

### CODE REVIEW

**Comment by jc00ke** [comment]
Overall looks great! Once we wrap up discussion I'll be happy to merge.

**Comment by botandrose** [comment]
Oh, what a great idea. I've done that, and replaced the other heredocs with `%(...)`, while I was at it.

**Comment by botandrose** [comment]
Yes, you are right. Turns out `before(:all)` will run at the beginning of every example group. I didn't know that!

**Comment by botandrose** [comment]
Forced push to get rid of the `fdescribe`. Should be good to go, now!

**Comment by jc00ke** [comment]
Happy New Year!

**Comment by botandrose** [comment]
:tada:

**Pull request merged**
