### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by shawnacscott**
Add a note about broken seed file on ruby versions we don't support

### CODE REVIEW

**Comment by reidab** [comment]
Which ruby versions was db:seed failing on?

**Comment by shawnacscott** [comment]
I believe from #299 & #300, 2.2 was failing. @squarism was helping people get set up, though, so he may have better knowledge.

**Comment by squarism** [comment]
2.2.0 was failing.  2.1.5 worked with a simple rvm switch and no other changes.

**Comment by botandrose** [comment]
Yes, Calagator currently only supports Ruby 2.0 and 2.1 because its still
on Rails 3.2, and that version of Rails does not work on Ruby 2.2. Work is
currently ongoing to support Rails 4.x, and thus Ruby 2.2.

**Comment by squarism** [comment]
Good to know the real reason (knowledge beyond calagator)!  Thanks for the info!

**Comment by botandrose** [comment]
Now that Calagator is distributed as a gem, we have put the supported versions of ruby directly in the gemspec, so Calagator will now fail to install on unsupported rubies with an informative error message:

```
ERROR:  Error installing calagator:
    calagator requires Ruby version < 2.2.0, >= 2.0.0.
```

Therefore, it should now be impossible to get the unhelpful failure @squarism experienced, so I think we can close this PR.

**Comment by botandrose** [comment]
Sure thing! We just underwent a big change in how calagator is installed, consumed, and developed, so any feedback on pain points is extremely valuable.

**Comment by shawnacscott** [comment]
Closing, since this is now redundant

**Pull request closed without merging**
