### PR TITLE
Drop support for Ruby 1.9

### PR DESCRIPTION
**Pull request by botandrose**
Any reason not to do this now, or should we wait for Rails 5?

### CODE REVIEW

**Comment by jc00ke** [comment]
I'm all for it, though @reidab's input is valuable here because he knows more about what other installs of Calagator run on.

**Comment by reidab** [comment]
I'm okay with dropping 1.9 support. We can't drop 2.0 support yet, because calagator.org is still deployed on a 2.0 series build.

**Comment by jc00ke** [comment]
Sounds reasonable to me. @botandrose can you rebase from master so we can merge here?

**Comment by botandrose** [comment]
Great! Rebased. Guess deleting tested lines effectively means less coverage %? Sorta makes sense...

**Pull request merged**
