### PR TITLE
Optimize mobile add-events page

### PR DESCRIPTION
**Pull request by jmcduffie32**
I based my changes on the mock-up in #371.

### CODE REVIEW

**Comment by reidab** [comment]
I looks like we have an intermittent build failure that's unrelated to this PR — I've restarted the failing build.

**Comment by shawnacscott** [comment]
Pretty! Thanks, @jmcduffie32! I don't think it's necessarily a reason to not merge this PR, but I'd love to see the "import event" and "add a venue" forms given this same lovely treatment!

**Comment by jmcduffie32** [comment]
@shawnacscott I've included the changes for those other two forms as well.

**Comment by shawnacscott** [comment]
Thanks, @jmcduffie32 & @PatHarryUX!

**Pull request merged**
