### PR TITLE
Flatten config variables in yml files

### PR DESCRIPTION
**Pull request by moedu23**
Flattening the variables in the yml files constitutes a breaking change. But I wanted to ask - should the variables stored in `themes/*/settings.yml` be moved to `config/secrets.yml`? 

See the previous discussions for pull request #274 and the original issue #158

### CODE REVIEW

**Comment by reidab** [comment]
The stuff in `themes/*/settings.yml` should be specific to the theme itself. We'd originally thought that this would include things like the site name and the timezone, but I think most of these make more sense moving into the deployment-specific `config` directory.

The only thing I think it makes sense to leave in the theme settings file is the `precompile_assets` key. This value shouldn't need to be customized outside of version control, so it will be save to use the existing SettingsReader class to parse it.

**Comment by moedu23** [comment]
In line with the discussion of turning Calagator into an engine... Let's merge the current PR and the next steps will be to:
1. Add figaro to call secrets and settings from ENV variables instead of `settings_reader.rb` and `secrets_reader.rb`
2. Create an initializer in the 'config' directory of the enclosing app (i.e. "some-calagator.org").

**Comment by botandrose** [comment]
:+1: I'd like to see this merged so we can replace the secrets system with Figaro in the engine.

**Comment by reidab** [comment]
@botandrose do you think we should work on merging this now and rebase the engine work on top of it, or work on merging the engine work and then rethink settings in that context?

**Comment by botandrose** [comment]
@reidab I just spoke to Maureen, and I'm leaning towards merging the engine work first, and then she and I can revisit this afterwards.

**Comment by moedu23** [comment]
Rebased these changes.

**Comment by botandrose** [comment]
:+1:

**Pull request merged**
