### PR TITLE
Update docs and view files to be clearer about customization

### PR DESCRIPTION
**Pull request by antislice**
- Add instructions to the INSTALL doc
- Change the text in the view files with replace-this-text to
be more explicit about what to do
- Change file path in about.html.erb to the views path instead
 of the themes path

### CODE REVIEW

**Comment by antislice** [comment]
Just updating a few things I ran into when setting up calagator with a new host application. I'm happy to make any wording changes that the maintainers like. I also changed the path of the file mentioned in `about.html.rb` because it looked like the themes thing didn't exist any more. (or doesn't exist yet)

(I'm planning on filing another issue or two about dependencies, and sending a general summary email about getting it set up from scratch to the dev list, but I figured this was a fairly minor & helpful fix I could do right away.)

**Comment by reidab** [comment]
Thanks! Please also add yourself to our [contributors list](https://github.com/calagator/calagator/blob/master/CONTRIBUTORS.md).

**Comment by reidab** [comment]
Thanks!

**Comment by antislice** [comment]
Sweet, thanks for merging!

**Pull request merged**
