### PR TITLE
Refactor machine tag handling

### PR DESCRIPTION
**Pull request by botandrose**
This refactors one of the last remaining bits of scary code.

* The `.machine_tags` method appears to be completely unused, so we can just delete it, which is my absolute favorite "refactoring" to do! Tests are still green, so its technically a refactoring, right?? :smile: 

* Break up complex `#machine_tag` method, and refactor into a composed method.

### CODE REVIEW

**Comment by botandrose** [comment]
Interesting, looks like coveralls still isn't rejecting on test coverage decreasing from 100%. Please don't merge this until I get coverage on this branch back up to 100%.

**Comment by botandrose** [comment]
Okay, this PR is good to go, but someone with access to the Coveralls configuration should try to decrease the threshold further. Reduction of -0.05% to 99.946% didn't trigger a failure.

**Comment by reidab** [comment]
My only argument in keeping `.machine_tags` would be that it will make implementation of #269 easier. That said, I'm okay removing it now and adding it back in if it's necessary later on.

**Comment by botandrose** [comment]
Yes, now that that issue references this PR, they can pull that method out of the diff if they want it. Until then, YAGNI.

**Comment by botandrose** [comment]
Hmm, now that I look at the diff one more time, I realize that I didn't check to see if any of the new extracted private methods collide with any methods on `Tag`, which this module is included into. And, even if they currently do not, these methods could be renamed, or `Tag`'s could be renamed in the future. This is a subtle trap for the future. I'm going to extract a new class and delegate to it, so that we only add the single `#machine_tag` method, which is unlikely to collide. So please hold off on merging until then!

**Comment by botandrose** [comment]
Okay, I'm much happier with this, now. Extracting `MachineTag` made several more beneficial refactorings more apparent.

* Configuration of `MachineTag`'s knowledge of specific providers is now done in an initializer instead of a constant, so it is now possible to configure and add additional providers without needing to overwrite a constant or know the original list.
* Reifying a machine tag object made it clear that the primary interface for collaborators (a hash) was guilty of primitive obsession. Now collaborators can just talk to the machine tag object itself.

Ready for review.

**Comment by reidab** [comment]
Also, tightened the coveralls threshold as requested.

**Comment by reidab** [comment]
Thanks! :palm_tree:

**Comment by botandrose** [comment]
Hooray!

**Pull request merged**
