### PR TITLE
Fixing use cases where end date or time are not set

### PR DESCRIPTION
**Pull request by sipple**
This addresses issue #16. 

* For new events, neither start_date/time nor end_date/time will be pre-populated.
* When start_date is set, end_date will be set accordingly even if blank.
* When start_Time is set, end_time will be set accordingly even if blank.
* In cases where there had not been an end_time set, a default duration of an hour is used to populate end_time.
* As start/end are not pre-populated in the view, the to_date and strftime calls would error when either values were blank. To fix, those formatting calls were moved into helpers that only run to_date and strftime when those values are set, and return an empty string if not.

(This request also adds the .idea/ project folder to the .gitignore file for Rubymine users like me. I hope that wasn't presumptuous of me.)

### CODE REVIEW

**Comment by shawnacscott** [comment]
Thanks for this, @sipple! I promise it'll get reviewed more soon, but @reidab is running this little thing called Open Source Bridge you may have heard of, so it may be a bit longer.

Currently, I'm not able to import events (using this as an example: http://www.meetup.com/PDX-Creative-Coders/events/222773733/) ont this branch. That being said, I'm also not able to do so on master. As far as I know, though, master is current with production, and I WAS able to import this event in production, so, I think we need to do a bit of troubleshooting on our end first.

**Comment by sipple** [comment]
I noticed this same problem when I was trying to first reproduce this error in the first place, @shawnacscott. I ended up testing this using a manually created new event without an end date, since the problem was specifically an event lacking that date regardless of how it came in (though import is the real world use case that causes this). Sorry I didn't report this; I thought at the time it was because I was trying to import an event from a few months ago, but it sounds like it may be a larger problem. Let me know if you need anything!

**Comment by shawnacscott** [comment]
One thing you could do now, @sipple. On further poking with a manually created event, I seem to be unable to:
 
* edit an existing event
* manually clear the end time
 * save it 

It gives me a validation error: "End time cannot be before start." That seems like unexpected behavior I'd like to see addressed. Thanks!

**Comment by sipple** [comment]
@shawnacscott, clarifying question: Is that all in sequence, or is there an overall problem with editing an event beyond clearing the end_date?

**Comment by shawnacscott** [comment]
Sorry for the confusion, I mean that any time an existing event has an end time cleared during editing it refuses to save.

**Comment by reidab** [comment]
Finally had a chance to review this — apologies for the long delay. It's working for me as expected. Thank you @sipple!

**Pull request merged**
