### PR TITLE
Add Figaro to set configuration variables in ENV

### PR DESCRIPTION
**Pull request by moedu23**
Refer to issue #158. 
Installed the Figaro gem to use the `application.yml` file to set configuration variables in ENV. Since Figaro is reading environment variables, this allowed us to remove `secrets_reader.rb` as well. We considered continuing to read environment variables from the `secrets.yml` file, but wanted to ensure that the introduction of Figaro was more obvious so we switched to `application.yml`. 
With help from @winescout.

### CODE REVIEW

**Comment by moedu23** [comment]
mixed up master branches locally...

**Comment by moedu23** [comment]
Upon further review, external solutions for this problem like Figaro, dotenv or the upgrade to Rails 4.1 would force a change in how ENV variables are stored. I'd planned on changing `SECRETS.mapping["provider"]` to `ENV['mapping']['provider']` for example, but Figaro and the other options do not support nested values.
Since this constitutes a breaking change, I wanted to see if there are thoughts on direction here?

PR is WIP!

**Comment by jc00ke** [comment]
I can't recall exactly why we decided to rewrite the existing code instead of using Figaro, but it seemed like the rewrite was the better option. @moedu23 do you remember?

**Comment by moedu23** [comment]
I don't remember talking about Figaro as an option when we started the first settings_reader PR. 

Stepping back a bit, currently `SecretsReader` is reading from the YAML file, but this process doesn't work on Heroku. Heroku needs to be able to read this information from ENV variables. The first solution was to create a separate class to help Heroku read those ENV variables. 

Does the fact that Figaro is doing the work of reading both ENV and YAML variables, (ENV will override YAML if both values are present) make it worth the breaking change of un-nesting values? Or is the un-nesting inevitable?

**Comment by winescout** [comment]
Addressing the nested yaml:
The requirement  forces us to use a flat config file instead of nested yaml like it currently is.  Figaro and other canned solutions don't support nested attrs because ENV doesn't.

This is a bit bigger breaking change than we hoped for when starting out, but conforming to the standard for Heroku feels like the greater good here and easier to understand for new users attempting to get the app running on that platform.

If we want to maintain the nested structure we can do a mapping during deployment like Tammer suggests here: (http://tammersaleh.com/posts/managing-heroku-environment-variables-for-local-development/)[http://tammersaleh.com/posts/managing-heroku-environment-variables-for-local-development/]  But I don't suggest that.

Great catch Moe.

**Comment by reidab** [comment]
Since we're already looking at combining things that had previously lived in themes/*/settings.yml and config/secrets.yml, I'm happy to migrate towards a flat structure for config information.

**Comment by reidab** [comment]
@botandrose ditto from #296: do you think we should work on merging this now and rebase the engine work on top of it, or work on merging the engine work and then rethink settings in that context?

**Comment by botandrose** [comment]
@reidab Yeah, this particular item might not be relevant after the engine work is merged, or at least not in this repo... probably would make sense on calagator/calagator.org.

**Comment by reidab** [comment]
Great. I'll close this for now and we'll reexamine it there later.

**Pull request closed without merging**
