### PR TITLE
Convert to Rails Engine

### PR DESCRIPTION
**Pull request by botandrose**
As discussed in #277, this PR converts the repo to an engine, and works in conjunction with the new calagator/calagator.org repo.

Interesting changes:
1. Tests are now run in a dummy app at `spec/dummy`
2. Models, Controllers, etc are now namespaced under the top-level `Calagator` module.
3. Theming has been removed, because the enclosing app is now the "theme," so to speak.
4. The `SETTINGS` constant has been removed, in favor of `mattr`s set on the top-level `Calagator` module, configured in an initializer in the app. Thanks @jamesmkur!

I'm not sure if its 100% ready to merge yet, but everything seems to work well, so I'll leave that judgement up to you guys. This branch is also threatening to become rather long-lived, which makes me nervous. :) Possible merge blockers that I'm aware of:

1. Assets are not namespaced.
2. Database tables are not namespaced.
3. README needs to be updated.
4. Default css and images?

These could be done in separate PRs after this is merged, though, to prevent `master` and `engine` branches from diverging too much.

What do you folks think?

### CODE REVIEW

**Comment by botandrose** [comment]
More development:
- @jamesmkur is back with a generator that will take a fresh rails install and turn it into a calagator.
- Need to remove Gemfile.lock again from the repo before this is good to merge. Currently running into failures related to jquery-ui gem changes.

**Comment by botandrose** [comment]
Okay, more development, all with the goal of getting calagator to work on a fresh rails install, and ensuring that that behavior is tested.

1. Big one first: users can bootstrap a new calagator install from scratch with the new `bin/calagator` executable. This wraps `rails new` and `rails g calagator:install` to make getting started with calagator super easy. We are also using this to bootstrap the `spec/dummy` folder for the tests (which is no longer in version control), so we have assurances that this gem works with a fresh rails install, and that the `calagator` binary and generator work. This also lays the groundwork for upgrading the versions of rails that we can support.

2. Turns out a lot of the code and tests related to dates and times were assuming a PST/PDT timezone, and would behave incorrectly in other timezones (fresh rails install has no timezone set). These assumptions have been fixed, and the tests now pick a random timezone to run the tests in to expose these shortcomings in the future.

3. jQuery and jQuery UI have been updated to work with a fresh rails install.

4. Calagator will now work without a secrets.yml, because fresh a rails install has none.

5. Calagator now only disables mass-assignment protection for its own models, not for the whole app.

6. Blacklist can now be configured via the calagator initializer, as well.

7. `application.css` and `application.js` have been renamed to `calagator.css` and `calagator.js`, respectively, and are inserted in the enclosing app by the generator.

8. There is now a unit test to make sure we're respecting `ENV["db"]` in Travis, and actually testing the db we think we are.

Phew. So that's a lot. This branch is getting scary long... I'm wondering if I should try to backport as many of these items as possible back to the master branch in separate PRs so they can be reviewed and merged one at a time to lay the groundwork for the big engine merge? Items 2, 3, 5, 8, certainly could be. Maybe a few misc commits from earlier...

Or, we could just bite the bullet and merge this whole thing at once. What do you guys think?

**Comment by reidab** [comment]
I'll try to review this in the next couple of days and see if it makes more sense to merge it wholesale or break things apart as you suggested.

We integrated a few changes to master from Saturday's code sprint, so we'll probably need to at least rebase this to get it amerceable again.

**Comment by botandrose** [comment]
Cool, I'll wait for your verdict on big merge vs break up, then I'll rebase. Sorry I missed the code sprint! Was looking forward to reviewing all this with you in person, but Real Life got in the way. :(

**Comment by dpritchett** [comment]
As a Spree developer I love the sound of this.  Would love to retrofit this onto the app we built off of `master` last weekend :)

**Comment by botandrose** [comment]
@dpritchett Fantastic! I would really really appreciate some feedback from someone who is actually trying to use the new engine, especially from the perspective of extension points. So far, the only client of the engine is the calagator.org website itself, so its not at all obvious where extension points are lacking.

That said, this PR is still WIP. I think its pretty much there, so I don't think too much will change, but I wouldn't totally trust this code until the PR gets merged and we get a 0.1.0.pre1 gem release out there.

**Comment by dpritchett** [comment]
For our calendar we added a Venue-derived model called Organization and we suppressed some form fields.  Organization has a really simple permalink-based auth system.  It's not exactly secured but it works for simple purposes.  Not sure that you'd need to change anything; Spree's style of handling Ruby overrides with .class_eval` and JS/ERB/CSS overrides by just making a local copy of the file has worked for me for a while.  It gets hairy when functionality gets super complex but calagator is nowhere near the size of Spree so I'm sure it's fine.

**Comment by botandrose** [comment]
@reidab Did you get a chance to review any of this? I've got some time this weekend that I could spend.

**Comment by botandrose** [comment]
This branch now has 100% test coverage. Shiny!

**Comment by reidab** [comment]
Nice!

I'm sorry for not getting a chance to review this sooner. :( 

I've pulled down a copy and have it running locally — I'll put things through their paces a bit more, but it's looking good so far. I also need to sit down for an hour or so and make sure everything's in place to deploy the new version to calagator.org once we're ready.

**Comment by botandrose** [comment]
Great! Do you want me to go ahead and rebase to get it mergable?

**Comment by botandrose** [comment]
@reidab I went ahead and rebased on top of all the recent changes, so this branch is mergeable again.

**Comment by reidab** [comment]
Great!  I think there may be one more admin change we want to get into production soon, but it should be a very easy rebase.

**Comment by reidab** [comment]
We may want to improve error handling with the project-level Rakefile a bit, since it depends on spec/dummy existing and this won't be the case in a fresh checkout.

**Comment by botandrose** [comment]
Agreed. Added a friendlier error message.

**Comment by dpritchett** [comment]
:birthday: :balloon: :tada:

**Comment by shawnacscott** [comment]
This is super exciting! Thanks for the epic, amazing work here, @botandrose @reidab @aeschright! 

:tada: :fireworks: :confetti_ball:

**Comment by botandrose** [comment]
Hot damn!

**Comment by botandrose** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by dnalot** [comment]
This looks great! `INSTALL.md` needs updated too.

**Pull request merged**
