### PR TITLE
deps: Update Ruby version to minimum of 2.5.0

### PR DESCRIPTION
**Pull request by reidab**

### CODE REVIEW

**Comment by kcomandich** [comment]
Here's an update to the docs to match: https://github.com/calagator/calagator/commit/71254c7ccc8ed14d82a7100f12be457e17422ad7 
Not sure I can add it to this pull request.

**Comment by aeschright** [comment]
@kcomandich I pulled in your docs commit.

**Comment by reidab** [comment]
This PR originally targeted 2.4 as our minimum Ruby version, but since 2.4 is EOL on March 31, I've removed it from the testing matrix and added 2.7. 

I've included a monkeypatch to get tests running on 2.6+, but since we're still on Rails 4.2 and it has no support for those versions I've allowed failures on them in Travis.

**Comment by reidab** [comment]
Merging despite the coveralls failure, since it looks to be from the simplecov update instead of any code changes.

**Pull request merged**
